DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE {
eid INT NOT NULL AUTO_INCREMENT,
firstName VARCHAR(25) NOT NULL,
lastName VARCHAR(25) NOT NULL,
position VARCHAR(25) NOT NULL,
PRIMARY KEY (eid)};

DROP TABLE IF EXISTS RATING;
CREATE TABLE RATING {
rID INT PRIMARY KEY ,
rater VARCHAR(25),
starRating INT ,
feedback VARCHAR(140)} 

DROP TABLE IF EXISTS CUSTOMER ;
CREATE TABLE CUSTOMER {
cid INT NOT NULL AUTO_INCREMENT,
firstName VARCHAR(25) NOT NULL,
lastName VARCHAR(25) NOT NULL,
rID INT,
FOREIGN KEY ( rID ) REFERENCES RATING(rID),
PRIMARY KEY (cid) };

DROP TABLE IF EXISTS MENU ;
CREATE TABLE MENU {
mID INT NOT NULL AUTO_INCREMENT,
item VARCHAR(25) UNIQUE NOT NULL,
description VARCHAR(100) NOT NULL,
price DECIMAL(10,2) NOT NULL,
type VARCHAR(15) NOT NULL,
quantityAvaiable INT NOT NULL,
PRIMARY KEY (mid) };


DROP TABLE IF EXISTS aTable ;
CREATE TABLE MENU {
tID INT NOT NULL AUTO_INCREMENT,
eID INT NOT NULL,
seats INT NOT NULL,
availability BOOLEAN NOT NULL,
PRIMARY KEY (tID) };

DROP TABLE IF EXISTS RECEIPT ;
CREATE TABLE RECEIPT {
receiptID INT NOT NULL AUTO_INCREMENT,
serverID INT NOT NULL ,
customerID INT NOT NULL,
subtotal DECIMAL(10,2) NOT NULL,
gratuity DECIMAL(10,2),
PRIMARY KEY (receiptID) ,
FOREIGN KEY ( serverID) REFERENCES EMPLOYEE(eID),
FOREIGN KEY (customerID) REFERENCES CUSTOMER(cID)
};
